export const countryToCode = {
	Argentina: "ar",
	Australia: "au",
	Austria: "at",
	Azerbaijan: "az",
	Bahrain: "bh",
	Belgium: "be",
	Brazil: "br",
	Canada: "ca",
	China: "cn",
	France: "fr",
	Germany: "de",
	Hungary: "hu",
	Italy: "it",
	Japan: "jp",
	Malaysia: "my",
	Mexico: "mx",
	Monaco: "mc",
	Netherlands: "nl",
	Portugal: "pt",
	Qatar: "qa",
	Russia: "ru",
	"Saudi Arabia": "sa",
	Singapore: "sg",
	"South Africa": "za",
	"South Korea": "kr",
	Spain: "es",
	Sweden: "se",
	Switzerland: "ch",
	Turkey: "tr",
	"United Arab Emirates": "ae",
	"Great Britain": "gb",
	"United Kingdom": "gb",
	"United States": "us",
};
